SELECT *
FROM (
    VALUES
        ('A5GbZKLwUM91CkKjKvan85No4VDQqMcV68yG9nLzqGXk', 'insider_lock_or_ops_pool', 'Insider lock or Ops pool', 'DO_NOT_USE_UNTIL_VERIFIED'),
        ('DDfCTd8HW29AmLHwqWfLREtG46iJsRrxceTHc77Xgw4H', 'insider_lock_or_ops_pool', 'Insider lock or Ops pool', 'DO_NOT_USE_UNTIL_VERIFIED'),
        ('FpwyBEgucz93BGNMoBqwFY9FEnLtu5av6qr1UxmEUR9R', 'insider_lock_or_ops_pool', 'Insider lock or Ops pool', 'DO_NOT_USE_UNTIL_VERIFIED'),
        ('DagafaFnDoackVFnqWfqTYDD4PKjT5hnzRZNaQg6LdLp', 'insider_lock_or_ops_pool', 'Insider lock or Ops pool', 'DO_NOT_USE_UNTIL_VERIFIED'),
        ('6k2SHJaMWy6TwLAQaAKnnGFUYp3gNgipxE33dbkCaf2Z', 'insider_lock_or_ops_pool', 'Insider lock or Ops pool', 'DO_NOT_USE_UNTIL_VERIFIED'),
        ('BXkmF1cAJqMwXWeTh4igLjD3XQ7nMw3fbtPRY8RR1DgQ', 'insider_lock_or_ops_pool', 'Insider lock or Ops pool', 'DO_NOT_USE_UNTIL_VERIFIED'),
        ('7Ko46nx9r9cPg9nitKjcX4BCyNqyRAfdaU7VUhq6eY8T', 'insider_lock_or_ops_pool', 'Insider lock or Ops pool', 'DO_NOT_USE_UNTIL_VERIFIED'),
        ('8WeWN41odRZt5Qe5VB9rYGt4yeH6FjfeKSsLS5vopdXo', 'insider_lock_or_ops_pool', 'Insider lock or Ops pool', 'DO_NOT_USE_UNTIL_VERIFIED'),
        ('Ce4eRUYL8xtofWMwrbqxZj1tx7qs8iuprV22iynpyfSo', 'insider_lock_or_ops_pool', 'Insider lock or Ops pool', 'DO_NOT_USE_UNTIL_VERIFIED'),
        ('8hiVWeu3i59xMNy1Jp72o4x1CHzFjKKbc78mhaxsF6wx', 'insider_lock_or_ops_pool', 'Insider lock or Ops pool', 'DO_NOT_USE_UNTIL_VERIFIED'),
        ('AMDupZnnuoZHoS1kHbipyTqqceHuh82Rp1qEwJpHEZPh', 'insider_lock_or_ops_pool', 'Insider lock or Ops pool', 'DO_NOT_USE_UNTIL_VERIFIED'),
        ('3aBbxLN19LNNFEfHYZYwJrQtV3vbWCyY9QMf1nuRdwo1', 'insider_lock_or_ops_pool', 'Insider lock or Ops pool', 'DO_NOT_USE_UNTIL_VERIFIED'),
        ('C2w7jQ8nbNVogepgjxwKBem9JYNWR3ocPc3eJsgpwPMC', 'insider_lock_or_ops_pool', 'Insider lock or Ops pool', 'DO_NOT_USE_UNTIL_VERIFIED'),
        ('Hwk2gsNVxEAGj7kz5Ex7Tu9wAWsctFoTe7KEbzrxBQj1', 'insider_lock_or_ops_pool', 'Insider lock or Ops pool', 'DO_NOT_USE_UNTIL_VERIFIED'),
        ('3bw4c64JkTPfZ9jcMXnAzbXXweb9by7TAQaWTKj6Yi4h', 'insider_lock_or_ops_pool', 'Insider lock or Ops pool', 'DO_NOT_USE_UNTIL_VERIFIED'),
        ('DF9rLSSMpJHrHeLz6twko9Ymv8fsKe2emq9dSEQp4HhZ', 'insider_lock_or_ops_pool', 'Insider lock or Ops pool', 'DO_NOT_USE_UNTIL_VERIFIED'),
        ('DeXjsmBPJiRWkrjoZm15Gjjea4LtDoXdVritNvVicUmg', 'insider_lock_or_ops_pool', 'Insider lock or Ops pool', 'DO_NOT_USE_UNTIL_VERIFIED'),
        ('As4nhNHHrhNZMoReGZvEbDTiooNmNATjyjjbadArEJVb', 'insider_lock_or_ops_pool', 'Insider lock or Ops pool', 'DO_NOT_USE_UNTIL_VERIFIED'),
        ('2pACwttxpQEk1gs62rZLn78Bb9iAjPvKptBYqwKVk7Ge', 'insider_lock_or_ops_pool', 'Insider lock or Ops pool', 'DO_NOT_USE_UNTIL_VERIFIED'),
        ('3W6AdCnjAKxA2GjrAJ48bt3n3wr9pG7F8jasrcciGAkf', 'insider_lock_or_ops_pool', 'Insider lock or Ops pool', 'DO_NOT_USE_UNTIL_VERIFIED'),
        ('DVVWXkWLio5MRGeopBMhGayEDJkPecz8T2Q8LxzEsEos', 'insider_lock_or_ops_pool', 'Insider lock or Ops pool', 'DO_NOT_USE_UNTIL_VERIFIED'),
        ('4EyVbx6MYCBk79LYQFSw1PZ74RFpvJ3TYP3ME7DgSuxB', 'insider_lock_or_ops_pool', 'Insider lock or Ops pool', 'DO_NOT_USE_UNTIL_VERIFIED'),
        ('GwzXxiNKZGZCqHQK1tzPP8ANyCS4YkYa5F6P9upPqrsb', 'insider_lock_or_ops_pool', 'Insider lock or Ops pool', 'DO_NOT_USE_UNTIL_VERIFIED'),
        ('Zg2CKtyca14FmBk4LPkkZEVnsYE4LNeyhQQsFE3hcNN', 'insider_lock_or_ops_pool', 'Insider lock or Ops pool', 'DO_NOT_USE_UNTIL_VERIFIED'),
        ('HhQAW4wtZYfbk7WmETgDMB4GtGwRBXtfiShngdjUpq1t', 'insider_lock_or_ops_pool', 'Insider lock or Ops pool', 'DO_NOT_USE_UNTIL_VERIFIED'),
        ('HYVem62h69nbyCJHdzwZsv7bKLL15D8egLeRcCkmfS2c', 'insider_lock_or_ops_pool', 'Insider lock or Ops pool', 'DO_NOT_USE_UNTIL_VERIFIED'),
        ('B3ePZXj66duAn2Zhgy2MXeUNacbMfHuZ1DukM49wK4oz', 'insider_lock_or_ops_pool', 'Insider lock or Ops pool', 'DO_NOT_USE_UNTIL_VERIFIED'),
        ('6rxSLPkpEQXDvyXeoRDVxyYrQvQpptPbZDox9qhJ1YgF', 'insider_lock_or_ops_pool', 'Insider lock or Ops pool', 'DO_NOT_USE_UNTIL_VERIFIED'),
        ('3mVqotZhkNrfi23NnVDrgLFHgvG6qQUUQwYUJbix5Vyp', 'insider_lock_or_ops_pool', 'Insider lock or Ops pool', 'DO_NOT_USE_UNTIL_VERIFIED'),
        ('4thbQayu3hLUZYrUHucup1MrqhEcxCj1aSKYFBEzLq9V', 'insider_lock_or_ops_pool', 'Insider lock or Ops pool', 'DO_NOT_USE_UNTIL_VERIFIED'),
        ('7eMLQvC6qkvqP7izpUdB3nJHzkeTu66UWLkRyTrAuBkS', 'insider_lock_or_ops_pool', 'Insider lock or Ops pool', 'DO_NOT_USE_UNTIL_VERIFIED'),
        ('EYNurCP6Mhp9nvdggCMHkYmhjwudUBcMfcz4qUXWgCS6', 'insider_lock_or_ops_pool', 'Insider lock or Ops pool', 'DO_NOT_USE_UNTIL_VERIFIED'),
        ('28uWRJsdBt3sM9GNZ7j39WHr8oXEZHFJtnN5m3pSchff', 'temporary_usage', 'Temporary usage', 'DO_NOT_USE_UNTIL_VERIFIED'),
        ('ATmkAJuCP117WTRLXZ9L5SBrMJpkcQoSGDgNf7rhGMaV', 'temporary_usage', 'Temporary usage', 'DO_NOT_USE_UNTIL_VERIFIED'),
        ('3duyMwKk6vpGQ9WjTfrwLacgA4KfaV6yM3YxXQQJ7ogV', 'temporary_usage', 'Temporary usage', 'DO_NOT_USE_UNTIL_VERIFIED'),
        ('5DNgfKSc4PJ9JmMneM6AdctVPkdi8cc3xgry8ksRtt95', 'temporary_usage', 'Temporary usage', 'DO_NOT_USE_UNTIL_VERIFIED'),
        ('DZgtrNzKLCKvU4ekf67kzohv3EW1hwdmDwPgiwXaGCZr', 'temporary_usage', 'Temporary usage', 'DO_NOT_USE_UNTIL_VERIFIED'),
        ('DY2rLdpbzDjDqUVHEvHQvPTShhM6xbJh4b5Po4DxXRV4', 'temporary_usage', 'Temporary usage', 'DO_NOT_USE_UNTIL_VERIFIED'),
        ('CV3nbqgvQm8NbQsudmKmr84zszJegLkrJkzrJY4X8znF', 'temporary_usage', 'Temporary usage', 'DO_NOT_USE_UNTIL_VERIFIED'),
        ('5dcpUq4r4TG3drg3JQSskGD1xGUepDguiJoMjj83G6hf', 'temporary_usage', 'Temporary usage', 'DO_NOT_USE_UNTIL_VERIFIED'),
        ('6PRskNzL8755ktdp25itkW8af6f1B3pGsQqjdMjjEZr1', 'temporary_usage', 'Temporary usage', 'DO_NOT_USE_UNTIL_VERIFIED'),
        ('eFttF7Ahk6haDqEsDgMQggKweDGxJd6u4CUQg1HkzDH', 'temporary_usage', 'Temporary usage', 'DO_NOT_USE_UNTIL_VERIFIED'),
        ('8i6bq2fYxDybk3foeaBXGen8s1pJFx5Vs4PDx38J6ho8', 'temporary_usage', 'Temporary usage', 'DO_NOT_USE_UNTIL_VERIFIED'),
        ('iwkwPri1U3PocwvxLBGLBrKCLvwSxLHch5aHbkaNuM3', 'temporary_usage', 'Temporary usage', 'DO_NOT_USE_UNTIL_VERIFIED'),
        ('9CkUYinXiHv1Juwgt4gzQjttvrxRzUeXEw4gurrs19Yu', 'temporary_usage', 'Temporary usage', 'DO_NOT_USE_UNTIL_VERIFIED'),
        ('DkBvptEyJaV4JFkd645rW7euVZobKWfNC9LGWziueYiR', 'temporary_usage', 'Temporary usage', 'DO_NOT_USE_UNTIL_VERIFIED'),
        ('EgUJL13AD9zkq8BeJ4f6t1BxLmeFdZEEb2Kvwz4K2odf', 'temporary_usage', 'Temporary usage', 'DO_NOT_USE_UNTIL_VERIFIED'),
        ('5PAjGzHJhdmBguP6DHAYpPLxCv1TydX9a1RZApMjM5n3', 'temporary_usage', 'Temporary usage', 'DO_NOT_USE_UNTIL_VERIFIED'),
        ('425VB7Phq4EApekN5qkrZWefeZwGwThThXhXT8SPbvtU', 'temp_dev_account', 'Temp Dev accounts', 'DO_NOT_USE_UNTIL_VERIFIED'),
        ('6kd4Z1rkto4y1PGQqfwNhxbEe7rcyP8TRsZ2PCiDR5r2', 'temp_dev_account', 'Temp Dev accounts', 'DO_NOT_USE_UNTIL_VERIFIED'),
        ('Exbfb9A4grsUNeuwf1aKeWDERQKmkTHjmUtfd5vLR5bq', 'temp_dev_account', 'Temp Dev accounts', 'DO_NOT_USE_UNTIL_VERIFIED'),
        ('7A6PQV93jCGfscAuRu69CuKyf5HPMQa9xqRBMrBT6Dvv', 'temp_dev_account', 'Temp Dev accounts', 'DO_NOT_USE_UNTIL_VERIFIED'),
        ('2oiMzQwp8JW1vLzuqHePgaLdoG1ypnn37nMjCSEy4tvK', 'insider_lock_or_ops_pool', 'Insider lock or Ops pool', 'DO_NOT_USE_UNTIL_VERIFIED'),
        ('9Su1HC6LNg8FVZH346xipVbEYUVvXr62nJX8Kbmk45CW', 'insider_lock_or_ops_pool', 'Insider lock or Ops pool', 'DO_NOT_USE_UNTIL_VERIFIED'),
        ('13UGBJmRx5eC2aRS1PVvdvQbA8XtnKrKNZp6XBinuakZ', 'insider_lock_or_ops_pool', 'Insider lock or Ops pool', 'DO_NOT_USE_UNTIL_VERIFIED'),
        ('4HAjZX8JA662tY5ptVTrXHu3nfz5oPLi1mkjhbh8VjFP', 'insider_lock_or_ops_pool', 'Insider lock or Ops pool', 'DO_NOT_USE_UNTIL_VERIFIED'),
        ('BuxUbBh4D7KBsNXRo283nihaQV8wZ6QDtudwrfyTAWBP', 'insider_lock_or_ops_pool', 'Insider lock or Ops pool', 'DO_NOT_USE_UNTIL_VERIFIED'),
        ('E72wWDCKCiS32SgEFocVs3EHEJTJkJRm58RRvpnLQcLz', 'insider_lock_or_ops_pool', 'Insider lock or Ops pool', 'DO_NOT_USE_UNTIL_VERIFIED'),
        ('BGMgUvHk6Yu1ouqjP2LM6Lwj3LEqdxqYaiu4p2QcN2CD', 'burn_account', 'Burn acct', 'DO_NOT_USE_UNTIL_VERIFIED'),
        ('6UE1gdvgFPbu8REp5YWKRkC5CZiXgwd7iEfTAqwbzUqV', 'burn_account', 'Burn acct', 'DO_NOT_USE_UNTIL_VERIFIED'),
        ('FUAExZHqG6C1HvXQABfy7vv2mR3CKcU4WPHEpQhUKFgb', 'insider_lock_or_ops_pool', 'Insider lock or Ops pool', 'DO_NOT_USE_UNTIL_VERIFIED')
) AS t(address, legacy_classification, legacy_comment, v3_supply_treatment)
